name: "Keplertech Formal"
description: ""
author: "keplertech"
branding:
  icon: "bar-chart-2"
  color: "blue"

inputs:
  design_home:
    description: "Path to the design home"
    required: true
  design_config:
    description: "Path to the design config"
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.design_home }}
    - ${{ inputs.design_config }}
